// <auto-generated />
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240507151200_mig9")]
    partial class mig9
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityLayer.Concrete.AboutUs", b =>
                {
                    b.Property<int>("AboutUsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AboutUsId"));

                    b.Property<string>("AboutUsContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutUsDanısman")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutUsFakulteBolum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutUsIsım")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutUsNumara")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutUsUniversite")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AboutUsId");

                    b.ToTable("AboutUs");

                    b.HasData(
                        new
                        {
                            AboutUsId = 1,
                            AboutUsContent = "Homomorfik Şifreleme'nin Anlatıldığı Wiki Web Sayfası",
                            AboutUsDanısman = "Dr. Öğr. Üyesi Ahmet ALBAYRAK",
                            AboutUsFakulteBolum = "Teknoloji Fakültesi Bilgisayar Mühendisliği",
                            AboutUsIsım = "Ali Berdan Karasoy",
                            AboutUsNumara = "182120015",
                            AboutUsUniversite = "Düzce Üniversitesi"
                        },
                        new
                        {
                            AboutUsId = 2,
                            AboutUsContent = "Homomorfik Şifreleme'nin Anlatıldığı Wiki Web Sayfası",
                            AboutUsDanısman = "Dr. Öğr. Üyesi Ahmet ALBAYRAK",
                            AboutUsFakulteBolum = "Teknoloji Fakültesi Bilgisayar Mühendisliği",
                            AboutUsIsım = "Yahya Arı",
                            AboutUsNumara = "182120004",
                            AboutUsUniversite = "Düzce Üniversitesi"
                        });
                });

            modelBuilder.Entity("EntityLayer.Concrete.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CategoryStatus")
                        .HasColumnType("bit");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 100,
                            CategoryDescription = "İçerik",
                            CategoryName = "Paragraph",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryID = 101,
                            CategoryDescription = "İçerik",
                            CategoryName = "Paragraph",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryID = 102,
                            CategoryDescription = "İçerik",
                            CategoryName = "Paragraph",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryID = 103,
                            CategoryDescription = "İçerik",
                            CategoryName = "Paragraph",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryID = 104,
                            CategoryDescription = "İçerik",
                            CategoryName = "Paragraph",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryID = 105,
                            CategoryDescription = "İçerik",
                            CategoryName = "Paragraph",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryID = 106,
                            CategoryDescription = "İçerik",
                            CategoryName = "Paragraph",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryID = 107,
                            CategoryDescription = "İçerik",
                            CategoryName = "Paragraph",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryID = 108,
                            CategoryDescription = "İçerik",
                            CategoryName = "Paragraph",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryID = 109,
                            CategoryDescription = "İçerik",
                            CategoryName = "Paragraph",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryID = 110,
                            CategoryDescription = "İçerik",
                            CategoryName = "Paragraph",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryID = 111,
                            CategoryDescription = "İçerik",
                            CategoryName = "Paragraph",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryID = 112,
                            CategoryDescription = "İçerik",
                            CategoryName = "Paragraph",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryID = 113,
                            CategoryDescription = "İçerik",
                            CategoryName = "Paragraph",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryID = 114,
                            CategoryDescription = "İçerik",
                            CategoryName = "Paragraph",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryID = 115,
                            CategoryDescription = "İçerik",
                            CategoryName = "Paragraph",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryID = 116,
                            CategoryDescription = "İçerik",
                            CategoryName = "Paragraph",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryID = 117,
                            CategoryDescription = "İçerik",
                            CategoryName = "Paragraph",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryID = 118,
                            CategoryDescription = "İçerik",
                            CategoryName = "Paragraph",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryID = 119,
                            CategoryDescription = "İçerik",
                            CategoryName = "Paragraph",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryID = 120,
                            CategoryDescription = "İçerik",
                            CategoryName = "Paragraph",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryID = 121,
                            CategoryDescription = "İçerik",
                            CategoryName = "Paragraph",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryID = 122,
                            CategoryDescription = "İçerik",
                            CategoryName = "Paragraph",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryID = 123,
                            CategoryDescription = "İçerik",
                            CategoryName = "Paragraph",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryID = 124,
                            CategoryDescription = "İçerik",
                            CategoryName = "Paragraph",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryID = 125,
                            CategoryDescription = "İçerik",
                            CategoryName = "Paragraph",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryID = 126,
                            CategoryDescription = "İçerik",
                            CategoryName = "Paragraph",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryID = 127,
                            CategoryDescription = "İçerik",
                            CategoryName = "Paragraph",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryID = 128,
                            CategoryDescription = "İçerik",
                            CategoryName = "Paragraph",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryID = 129,
                            CategoryDescription = "İçerik",
                            CategoryName = "Paragraph",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryID = 130,
                            CategoryDescription = "İçerik",
                            CategoryName = "Paragraph",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryID = 131,
                            CategoryDescription = "İçerik",
                            CategoryName = "Paragraph",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryID = 132,
                            CategoryDescription = "İçerik",
                            CategoryName = "Paragraph",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryID = 133,
                            CategoryDescription = "İçerik",
                            CategoryName = "Paragraph",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryID = 134,
                            CategoryDescription = "İçerik",
                            CategoryName = "Paragraph",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryID = 135,
                            CategoryDescription = "İçerik",
                            CategoryName = "Paragraph",
                            CategoryStatus = true
                        });
                });

            modelBuilder.Entity("EntityLayer.Concrete.Example", b =>
                {
                    b.Property<int>("ExampleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExampleId"));

                    b.Property<string>("ExampleContent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExampleId");

                    b.ToTable("Example");

                    b.HasData(
                        new
                        {
                            ExampleId = 1,
                            ExampleContent = " using System;\r\n				using Microsoft.Research.SEAL;\r\n				namespace HomomorphicEncryptionExample {\r\n				class Program {\r\n				static void Main(string[] args) {\r\n				// SEAL kütüphanesini kullanarak homomorfik şifreleme örneği\r\n				// Parametrelerin oluşturulması\r\n				EncryptionParameters parms = new EncryptionParameters(SchemeType.BFV);\r\n				parms.PolyModulusDegree = 4096;\r\n				parms.CoeffModulus = CoeffModulus.BFVDefault(polyModulusDegree: 4096);\r\n				parms.PlainModulus = new Modulus(40961);\r\n				using(SEALContext context = new SEALContext(parms))\r\n				{\r\n				// Anahtar çiftlerinin oluşturulması\r\n				KeyGenerator keygen = new KeyGenerator(context);\r\n				PublicKey publicKey = keygen.PublicKey;\r\n				SecretKey secretKey = keygen.SecretKey;\r\n				// Encryptor ve Decryptor'ların oluşturulması\r\n				Encryptor encryptor = new Encryptor(context, publicKey);\r\n				Decryptor decryptor = new Decryptor(context, secretKey);\r\n				// Verinin şifrelenmesi\r\n				Plaintext plainText = new Plaintext(\"42\");\r\n				Console.WriteLine(\"Original: \" + plainText.ToString());\r\n				Ciphertext encryptedData = new Ciphertext();\r\n				encryptor.Encrypt(plainText, encryptedData);\r\n				Console.WriteLine(\"Encrypted: \" + encryptedData.ToString());\r\n				// Verinin şifresinin çözülmesi\r\n				Plaintext decryptedData = new Plaintext();\r\n				decryptor.Decrypt(encryptedData, decryptedData);\r\n				Console.WriteLine(\"Decrypted: \" + decryptedData.ToString());\r\n				}\r\n				}\r\n				}\r\n				}"
                        },
                        new
                        {
                            ExampleId = 2,
                            ExampleContent = " import com.n1analytics.paillier.*;\r\n				public class HomomorphicEncryptionExample {\r\n				public static void main(String[] args) {\r\n				try {\r\n				// Paillier anahtar çiftlerini oluştur\r\n				PaillierPrivateKey privateKey = PaillierPrivateKey.create(2048);\r\n				PaillierPublicKey publicKey = privateKey.getPublicKey();\r\n				// Şifrelenecek sayıları oluştur\r\n				long plaintext1 = 42;\r\n				long plaintext2 = 15;\r\n				// Sayıları şifrele\r\n				Ciphertext ciphertext1 = publicKey.encrypt(plaintext1);\r\n				Ciphertext ciphertext2 = publicKey.encrypt(plaintext2);\r\n				// Şifreli sayıları topla\r\n				Ciphertext sumCiphertext = ciphertext1.add(ciphertext2);\r\n				// Toplamı çöz\r\n				long decryptedSum = privateKey.decrypt(sumCiphertext).longValue();\r\n				// Sonuçları ekrana yazdır\r\n				System.out.println(\"Plaintext 1: \" + plaintext1);\r\n				System.out.println(\"Plaintext 2: \" + plaintext2);\r\n				System.out.println(\"Encrypted 1: \" + ciphertext1.toString());\r\n				System.out.println(\"Encrypted 2: \" + ciphertext2.toString());\r\n				System.out.println(\"Sum (Encrypted): \" + sumCiphertext.toString());\r\n				System.out.println(\"Decrypted Sum: \" + decryptedSum);\r\n				} catch (PaillierException e) {\r\n				 e.printStackTrace();\r\n				 }\r\n				}\r\n				}"
                        },
                        new
                        {
                            ExampleId = 3,
                            ExampleContent = "var csharpCode3 = `\r\n				from seal import *\r\n				def main():\r\n				# SEALContext ve Encoder'ın oluşturulması\r\n				parms = EncryptionParameters(scheme_type.BFV)\r\n				parms.set_poly_modulus_degree(4096)\r\n				parms.set_coeff_modulus(CoeffModulus.BFVDefault(4096))\r\n				parms.set_plain_modulus(PlainModulus(40961))\r\n				context = SEALContext(parms)\r\n				encoder = IntegerEncoder(context)\r\n				# Anahtar çiftlerinin oluşturulması\r\n				keygen = KeyGenerator(context)\r\n				public_key = keygen.public_key()\r\n				secret_key = keygen.secret_key()\r\n				# Encryptor ve Decryptor'ların oluşturulması\r\n				 encryptor = Encryptor(context, public_key)\r\n				decryptor = Decryptor(context, secret_key)\r\n				# Verinin şifrelenmesi\r\n				plain_text_1 = 42\r\n				plain_text_2 = 15\r\n				encrypted_data_1 = Ciphertext()\r\n				encrypted_data_2 = Ciphertext()\r\n				encryptor.encrypt(encoder.encode(plain_text_1), encrypted_data_1)\r\n				encryptor.encrypt(encoder.encode(plain_text_2), encrypted_data_2)\r\n				# Şifreli sayıların toplanması\r\n				encrypted_sum = Ciphertext()\r\n				evaluator = Evaluator(context)\r\n				evaluator.add(encrypted_data_1, encrypted_data_2, encrypted_sum)\r\n				# Şifreli toplamın çözülmesi\r\n				 decrypted_sum = Plaintext()\r\n				 decryptor.decrypt(encrypted_sum, decrypted_sum)\r\n				 # Sonuçların ekrana yazdırılması\r\n				print(\"Plaintext 1:\", plain_text_1)\r\n				  print(\"Plaintext 2:\", plain_text_2)\r\n				   print(\"Encrypted 1:\", encrypted_data_1.to_string())\r\n				   print(\"Encrypted 2:\", encrypted_data_2.to_string())\r\n				 print(\"Encrypted Sum:\", encrypted_sum.to_string())\r\n				 print(\"Decrypted Sum:\", encoder.decode_int64(decrypted_sum))\r\n				if _name_ == '_main_':\r\n				    main()\r\n				`;"
                        });
                });

            modelBuilder.Entity("EntityLayer.Concrete.Lecture", b =>
                {
                    b.Property<int>("LectureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LectureId"));

                    b.Property<string>("LectureContent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LectureId");

                    b.ToTable("Lectures");

                    b.HasData(
                        new
                        {
                            LectureId = 1,
                            LectureContent = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
                        });
                });

            modelBuilder.Entity("EntityLayer.Concrete.Paragraph", b =>
                {
                    b.Property<int>("ParagraphID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParagraphID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("ParagraphContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ParagraphStatus")
                        .HasColumnType("bit");

                    b.Property<string>("ParagraphTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ParagraphID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Paragraphs");

                    b.HasData(
                        new
                        {
                            ParagraphID = 100,
                            CategoryID = 100,
                            ParagraphContent = "Toplama homomorfizmi (fully homomorphic encryption, FHE), çıkarma homomorfizmi (partially homomorphic encryption, PHE),\r\n				ve çarpma homomorfizmi (somewhat homomorphic encryption).",
                            ParagraphStatus = true,
                            ParagraphTitle = "Temelde üç tür homomorfik şifreleme vardır:"
                        },
                        new
                        {
                            ParagraphID = 101,
                            CategoryID = 101,
                            ParagraphContent = "Bu tür homomorfizm, şifreli veri üzerinde herhangi bir matematiksel işlemi gerçekleştirmeye izin verir.\r\n				Yani şifrelenmiş sayılar üzerinde toplama, çıkarma, çarpma ve bölme işlemleri yapılabilir.\r\n				Fully homomorfik şifreleme, tamamen genel matematiksel işlemleri destekler. Ancak,\r\n				bu tür şifreleme yöntemleri genellikle hesaplama maliyeti ve karmaşıklığı yüksek olduğundan,\r\n				pratik uygulamalarda kullanımı biraz sınırlı olabilir.",
                            ParagraphStatus = true,
                            ParagraphTitle = "1. Toplama Homomorfizmi (Fully Homomorphic Encryption - FHE):"
                        },
                        new
                        {
                            ParagraphID = 102,
                            CategoryID = 102,
                            ParagraphContent = "PHE, şifreli metin üzerinde belirli türde matematiksel işlemleri gerçekleştirmeye izin verir.\r\n				Genellikle toplama veya çarpma işlemlerine izin veren bir homomorfizm türüdür.\r\n				PHE, özellikle belirli uygulamalar için daha hızlı ve daha az hesaplama maliyetine sahiptir.\r\n				Ancak tam anlamıyla genel işlemleri desteklemez.",
                            ParagraphStatus = true,
                            ParagraphTitle = "2. Çıkarma Homomorfizmi (Partially Homomorphic Encryption - PHE):"
                        },
                        new
                        {
                            ParagraphID = 103,
                            CategoryID = 103,
                            ParagraphContent = "Somewhat homomorfik şifreleme, genellikle çarpma işlemlerine izin veren bir homomorfizm türüdür.\r\n				Bu, genellikle veri analitiği gibi belirli uygulamalarda kullanışlıdır.\r\n				Bu tür şifreleme yöntemleri, genellikle belirli sayıda çarpma işlemine izin verir. Bu sınırlama,\r\n				tamamen genel olmayan bir homomorfizmi temsil eder.",
                            ParagraphStatus = true,
                            ParagraphTitle = "3. Çarpma Homomorfizmi (Somewhat Homomorphic Encryption):"
                        },
                        new
                        {
                            ParagraphID = 104,
                            CategoryID = 104,
                            ParagraphContent = "Homomorfik şifreleme, gizliliğin korunması ve güvenli veri işleme konularında önemli bir rol oynar.\r\n				Özellikle bulut bilişim ve veri paylaşımı gibi alanlarda, verilerin şifrelenmiş hali üzerinde işlemler yapılabilmesi,\r\n				hem gizliliği hem de güvenliği artırabilir. Ancak, homomorfik şifreleme yöntemleri genellikle daha karmaşık ve hesaplama maliyeti yüksek olduğu için,\r\n				pratik uygulamalarda dikkatlice değerlendirilmelidir.",
                            ParagraphStatus = true,
                            ParagraphTitle = "Homomorfik Wiki"
                        },
                        new
                        {
                            ParagraphID = 105,
                            CategoryID = 105,
                            ParagraphContent = "Homomorfik şifreleme, şifrelenmiş veriler üzerinde işlem yapmayı mümkün kılan bir şifreleme yöntemidir. Bu yöntem sayesinde, veriler şifrelenmiş haldeyken bile matematiksel işlemler uygulanabilir ve sonuçlar şifrelenmiş olarak kalır. Bu, verilerin gizliliğini koruyarak, dış kaynaklı hesaplama ve depolamaya olanak tanır.",
                            ParagraphStatus = true,
                            ParagraphTitle = "Homomorfik Wiki Açıklama"
                        },
                        new
                        {
                            ParagraphID = 106,
                            CategoryID = 106,
                            ParagraphContent = "Özellikle sağlık sektöründe, homomorfik şifreleme, hassas tıbbi verilerin güvenli bir şekilde işlenmesini sağlar. Bu sayede, sağlık hizmetleri, gizlilik endişelerini azaltarak, veri analitiği ve tahmine dayalı analiz gibi önemli hizmetleri daha etkin bir şekilde kullanabilirler.",
                            ParagraphStatus = true,
                            ParagraphTitle = "Homomorfik Wiki Açıklama"
                        },
                        new
                        {
                            ParagraphID = 107,
                            CategoryID = 107,
                            ParagraphContent = "Homomorfik şifreleme, şifrelenmiş veriler üzerinde farklı hesaplama sınıfları gerçekleştirebilen birden fazla şifreleme şeması türünü içerir.\r\n				Hesaplamalar Boolean veya aritmetik devreler olarak temsil edilir. Bazı yaygın homomorfik şifreleme türleri kısmen homomorfik,\r\n				biraz homomorfik, seviyeli tamamen homomorfik ve tamamen homomorfik şifrelemedir:",
                            ParagraphStatus = true,
                            ParagraphTitle = "Homomorfik Wiki Açıklama"
                        },
                        new
                        {
                            ParagraphID = 108,
                            CategoryID = 108,
                            ParagraphContent = "Kısmen homomorfik şifreleme, örneğin toplama veya çarpma gibi yalnızca tek tip kapıdan oluşan devrelerin\r\n					değerlendirilmesini destekleyen şemaları kapsar.",
                            ParagraphStatus = true,
                            ParagraphTitle = "Homomorfik Wiki Açıklama"
                        },
                        new
                        {
                            ParagraphID = 109,
                            CategoryID = 109,
                            ParagraphContent = "Bir dereceye kadar homomorfik şifreleme şemaları, iki tür kapıyı değerlendirebilir,\r\n					ancak yalnızca devrelerin bir alt kümesi için.\r\n					Seviyelendirilmiş tamamen homomorfik şifreleme, sınırlı (önceden belirlenmiş) derinliğe sahip\r\n					birden fazla kapı türünden oluşan rastgele devrelerin değerlendirilmesini destekler.",
                            ParagraphStatus = true,
                            ParagraphTitle = "Homomorfik Wiki Açıklama"
                        },
                        new
                        {
                            ParagraphID = 110,
                            CategoryID = 110,
                            ParagraphContent = "Tamamen homomorfik şifreleme (FHE), sınırsız derinlikte birden fazla kapı türünden oluşan rastgele\r\n					devrelerin değerlendirilmesine olanak tanır ve homomorfik şifrelemenin en güçlü kavramıdır.",
                            ParagraphStatus = true,
                            ParagraphTitle = "Homomorfik Wiki Açıklama"
                        },
                        new
                        {
                            ParagraphID = 111,
                            CategoryID = 111,
                            ParagraphContent = "Homomorfik şifreleme şemalarının çoğunluğu için, devrelerin çarpımsal derinliği,\r\n				şifrelenmiş veriler üzerinde hesaplamaların gerçekleştirilmesindeki temel pratik sınırlamadır.\r\n				Homomorfik şifreleme şemaları doğası gereği şekillendirilebilir . İşlenebilirlik açısından, homomorfik şifreleme şemaları,\r\n				homomorfik olmayan şemalara göre daha zayıf güvenlik özelliklerine sahiptir.",
                            ParagraphStatus = true,
                            ParagraphTitle = "Homomorfik Wiki Açıklama"
                        },
                        new
                        {
                            ParagraphID = 112,
                            CategoryID = 112,
                            ParagraphContent = "\"Homomorfik şifreleme, verilerin gizliliğini koruyarak aynı zamanda şifreli biçimde işlenmelerine olanak tanıyan bir kriptografik ilerlemedir, bu da güvenli veri analizi ve işleme için önemli bir çığır açmaktadır.\"",
                            ParagraphStatus = true,
                            ParagraphTitle = "Homomorfik Wiki Açıklama"
                        },
                        new
                        {
                            ParagraphID = 113,
                            CategoryID = 113,
                            ParagraphContent = "Homomorfik şifreleme kavramı, modern kriptografi araştırmalarının bir sonucu olarak ortaya çıkmıştır. İlk homomorfik şifreleme protokolü, 1978 yılında Ron Rivest, Adi Shamir ve Leonard Adleman (RSA olarak da bilinir) tarafından geliştirilen RSA şifrelemesinden birkaç yıl sonra ortaya çıktı.\r\n\r\n				Ancak, tam homomorfik şifreleme protokolü ilk kez 2009 yılında Craig Gentry tarafından tanıtıldı. Gentry'nin çalışması, matematiksel olarak karmaşık bir yapı kullanarak, şifreli veriler üzerinde toplama ve çarpma işlemlerini gerçekleştirebilecek bir protokol sunuyordu. Bu, veri gizliliği açısından devrim niteliğinde bir adımdı, çünkü daha önce, şifreli veriler üzerinde işlem yapmak, genellikle verinin şifresini çözmeyi gerektirirdi.",
                            ParagraphStatus = true,
                            ParagraphTitle = "Tarihçe"
                        },
                        new
                        {
                            ParagraphID = 114,
                            CategoryID = 114,
                            ParagraphContent = "Gentry'nin çalışması, homomorfik şifrelemenin potansiyelini gösterdi, ancak pratikte kullanılabilirliği sınırlıydı çünkü hesaplama maliyeti oldukça yüksekti. Ancak, daha sonraki yıllarda, araştırmacılar homomorfik şifreleme protokollerini iyileştirmek ve daha etkili hale getirmek için çeşitli yaklaşımlar geliştirdiler.\r\n\r\n				2013 yılında, Gentry ve Zvika Brakerski, daha etkili ve kullanılabilir bir kısmi homomorfik şifreleme protokolü tanıttılar. Bu protokol, işlemlerin sayısını ve hesaplama maliyetini azaltarak daha pratik bir kullanım sağladı.",
                            ParagraphStatus = true,
                            ParagraphTitle = "Tarihçe"
                        },
                        new
                        {
                            ParagraphID = 115,
                            CategoryID = 115,
                            ParagraphContent = "Tamamen homomorfik bir şifreleme şeması oluşturma sorunu ilk olarak 1978'de, RSA şemasının yayınlanmasından sonraki bir yıl içinde önerildi. 30 yılı aşkın süredir bir çözümün var olup olmadığı belirsizdi. Bu dönemde kısmi sonuçlar aşağıdaki şemaları içeriyordu:",
                            ParagraphStatus = true,
                            ParagraphTitle = "FHE, Tam Homomorfik Şifreleme (Fully Homomorphic Encryption)"
                        },
                        new
                        {
                            ParagraphID = 116,
                            CategoryID = 116,
                            ParagraphContent = "RSA şifreleme sistemi (sınırsız sayıda modüler çarpma)",
                            ParagraphStatus = true,
                            ParagraphTitle = "FHE, Tam Homomorfik Şifreleme (Fully Homomorphic Encryption)"
                        },
                        new
                        {
                            ParagraphID = 117,
                            CategoryID = 117,
                            ParagraphContent = "ElGamal şifreleme sistemi (sınırsız sayıda modüler çarpma)",
                            ParagraphStatus = true,
                            ParagraphTitle = "FHE, Tam Homomorfik Şifreleme (Fully Homomorphic Encryption)"
                        },
                        new
                        {
                            ParagraphID = 118,
                            CategoryID = 118,
                            ParagraphContent = "Boneh – Goh – Nissim kripto sistemi (sınırsız sayıda toplama işlemi ancak en fazla bir çarpma)",
                            ParagraphStatus = true,
                            ParagraphTitle = "FHE, Tam Homomorfik Şifreleme (Fully Homomorphic Encryption)"
                        },
                        new
                        {
                            ParagraphID = 119,
                            CategoryID = 119,
                            ParagraphContent = "Goldwasser – Micali şifreleme sistemi (sınırsız sayıda özel veya işlem)",
                            ParagraphStatus = true,
                            ParagraphTitle = "FHE, Tam Homomorfik Şifreleme (Fully Homomorphic Encryption)"
                        },
                        new
                        {
                            ParagraphID = 120,
                            CategoryID = 120,
                            ParagraphContent = "Sander-Young-Yung sistemi (20 yıldan fazla bir süre sonra logaritmik derinlik devreleri sorununu çözdü)",
                            ParagraphStatus = true,
                            ParagraphTitle = "FHE, Tam Homomorfik Şifreleme (Fully Homomorphic Encryption)"
                        },
                        new
                        {
                            ParagraphID = 121,
                            CategoryID = 121,
                            ParagraphContent = "Benaloh şifreleme sistemi (sınırsız sayıda modüler ekleme)",
                            ParagraphStatus = true,
                            ParagraphTitle = "FHE, Tam Homomorfik Şifreleme (Fully Homomorphic Encryption)"
                        },
                        new
                        {
                            ParagraphID = 122,
                            CategoryID = 122,
                            ParagraphContent = "Ishai-Paskin şifreleme sistemi (polinom boyutunda dallanma programları)",
                            ParagraphStatus = true,
                            ParagraphTitle = "FHE, Tam Homomorfik Şifreleme (Fully Homomorphic Encryption)"
                        },
                        new
                        {
                            ParagraphID = 123,
                            CategoryID = 123,
                            ParagraphContent = "Paillier şifreleme sistemi (sınırsız sayıda modüler ekleme)",
                            ParagraphStatus = true,
                            ParagraphTitle = "FHE, Tam Homomorfik Şifreleme (Fully Homomorphic Encryption)"
                        },
                        new
                        {
                            ParagraphID = 124,
                            CategoryID = 124,
                            ParagraphContent = "Homomorfik şifreleme alanı hala aktif olarak araştırılmaktadır ve gelecekte daha gelişmiş ve etkili protokollerin ortaya çıkması muhtemeldir. Bu teknolojinin, gizlilik odaklı uygulamalarda ve bulut bilişim gibi alanlarda daha yaygın olarak kullanılması beklenmektedir.",
                            ParagraphStatus = true,
                            ParagraphTitle = "FHE, Tam Homomorfik Şifreleme (Fully Homomorphic Encryption)"
                        },
                        new
                        {
                            ParagraphID = 125,
                            CategoryID = 125,
                            ParagraphContent = "\"Homomorfik, cebirdeki homomorfizmi ifade eder : şifreleme ve şifre çözme fonksiyonları, düz metin ve şifreli metin uzayları arasındaki homomorfizmler olarak düşünülebilir.\"",
                            ParagraphStatus = true,
                            ParagraphTitle = "blockquote"
                        },
                        new
                        {
                            ParagraphID = 126,
                            CategoryID = 126,
                            ParagraphContent = "Homomorfik şifreleme, şifreli veriler üzerinde matematiksel işlemler yapmayı mümkün kılan bir kriptografik tekniktir. Bu teknik, çeşitli kullanım senaryolarında çeşitli avantajlar sağlar. İşte homomorfik şifreleme ile yapılabilecek bazı şeyler:",
                            ParagraphStatus = true,
                            ParagraphTitle = "Homomorfik şifreleme ile neler yapılabilir?"
                        },
                        new
                        {
                            ParagraphID = 127,
                            CategoryID = 127,
                            ParagraphContent = "Veritabanları veya bulut tabanlı hizmetlerdeki hassas veriler, homomorfik şifreleme ile şifrelenerek işlenebilir.\r\n					Örneğin, bir bulut hizmet sağlayıcısı, şifreli veriler üzerinde hesaplamalar yapabilir ve sonuçları müşterilere geri gönderebilir,\r\n					ancak verilerin içeriğine erişim sağlayamaz.",
                            ParagraphStatus = true,
                            ParagraphTitle = "Koruma:"
                        },
                        new
                        {
                            ParagraphID = 128,
                            CategoryID = 128,
                            ParagraphContent = "Homomorfik şifreleme, verilerin gizliliğini korurken bulutta güvenli hesaplamalar yapmayı mümkün kılar. Bu, kişisel veya hassas verilerin güvenli bir şekilde işlenmesini sağlar.",
                            ParagraphStatus = true,
                            ParagraphTitle = "Gizlilik Korunarak Hesaplama Yapma:"
                        },
                        new
                        {
                            ParagraphID = 129,
                            CategoryID = 129,
                            ParagraphContent = "Hastane kayıtları gibi özel sağlık verileri, homomorfik şifreleme kullanılarak güvenli bir şekilde işlenebilir. Bu sayede, sağlık hizmeti sağlayıcıları,\r\n					hastaların verileri üzerinde analizler yapabilirken verilerin gizliliği korunmuş olur.",
                            ParagraphStatus = true,
                            ParagraphTitle = "Sağlık Sektörü:"
                        },
                        new
                        {
                            ParagraphID = 130,
                            CategoryID = 130,
                            ParagraphContent = "Homomorfik şifreleme, şifreli veriler üzerinde analiz ve madencilik yapılmasını mümkün kılar. Örneğin, bir bulutta depolanan ve homomorfik olarak şifrelenmiş sağlık verileri üzerinde analiz yapılabilir, ancak verilerin gizliliği korunur.",
                            ParagraphStatus = true,
                            ParagraphTitle = "Veri Analitiği ve Veri Madenciliği:"
                        },
                        new
                        {
                            ParagraphID = 131,
                            CategoryID = 131,
                            ParagraphContent = "Homomorfik şifreleme, verilerin dış kaynaklara güvenli bir şekilde aktarılmasını sağlar. Bu, hassas verilerin bulut ortamlarında depolanmasını veya üçüncü taraf hizmet sağlayıcılarına aktarılmasını mümkün kılar.",
                            ParagraphStatus = true,
                            ParagraphTitle = "Outsourcing ve Veri Depolama:"
                        },
                        new
                        {
                            ParagraphID = 132,
                            CategoryID = 132,
                            ParagraphContent = "Homomorfik şifreleme, verilerin güvenli bir şekilde paylaşılmasını sağlar. Örneğin, farklı kurumlar veya kullanıcılar arasında hassas verilerin paylaşılması gerektiğinde, bu veriler homomorfik olarak şifrelenebilir ve güvenli bir şekilde paylaşılabilir.",
                            ParagraphStatus = true,
                            ParagraphTitle = "Güvenli Veri Paylaşımı:"
                        },
                        new
                        {
                            ParagraphID = 133,
                            CategoryID = 133,
                            ParagraphContent = "Homomorfik şifreleme, veri sahiplerinin verilerini paylaşma konusundaki endişelerini azaltır. Bu, veri analizine katılımı teşvik eder ve daha geniş veri setlerinin kullanılmasını sağlar.",
                            ParagraphStatus = true,
                            ParagraphTitle = "Veri Analizine Katılımı Teşvik Etmek:"
                        },
                        new
                        {
                            ParagraphID = 134,
                            CategoryID = 134,
                            ParagraphContent = "Finansal veriler, müşteri bilgileri veya finansal işlemler, homomorfik şifreleme ile güvence altına alınabilir. Bu sayede, finansal analizler yapılabilirken müşteri gizliliği korunabilir.",
                            ParagraphStatus = true,
                            ParagraphTitle = "Finansal Hizmetler:"
                        },
                        new
                        {
                            ParagraphID = 135,
                            CategoryID = 135,
                            ParagraphContent = "Homomorfik şifreleme, veri işleme ihtiyacını ortadan kaldırarak, verilerin güvenliğini artırır. Böylelikle, verilerin güvenliği için endişe duyan kurumlar ve kullanıcılar, verilerini şifreleyerek dış kaynaklara güvenle aktarabilirler.",
                            ParagraphStatus = true,
                            ParagraphTitle = "Açıklama"
                        });
                });

            modelBuilder.Entity("EntityLayer.Concrete.Paragraph", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Category", "Category")
                        .WithMany("Paragraphs")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Category", b =>
                {
                    b.Navigation("Paragraphs");
                });
#pragma warning restore 612, 618
        }
    }
}
